### PR TITLE
New attribute page_img: logos for for pages and sections

### PR DESCRIPTION
**Pull request by PhilReedData**
As discussed, I have borrowed the `image` page attribute from RO-Crate and used a new `page_img` attribute for pages to show a graphic such as a logo to the side of the page title. It also shows on the section navigation cards. There is no change to the rendered HTML in either place unless the `page_img` attribute appears in the front-matter of a page.

More details and images are [described in a Google Doc](https://docs.google.com/document/d/1VSpqcx_Jjwq0W_D-m7shmRB4Xpc5gD8qM5ZmNCwuKRk/edit?tab=t.0).

This has been tested on a branch of the FAIRDOM website, and in the ETT site itself. I used the following code in `_config.yml` to make a remote call:
`remote_theme: PhilReedData/elixir-toolkit-theme@page-img-007`

This is a fork from version 3.2.0. I did not mean to change the Gemfile.lock file. 

### To do

- [x] Further testing on other sites.
- [x] Tweak the image sizes for mobile viewport and particularly wide/narrow images.
- [ ] Perhaps a flag to turn the feature off in section navigation and/or pages.

### Sample images 
More images in the linked Google Doc above.
image
image
imageimage
image
image

### CODE REVIEW

**Comment by bedroesb** [comment]
@PhilReedData Hey! Sorry it took so long to look at your pull request. I played around with some bootstrap classes. Could you have a look in how it behaves on your deployment?

**Comment by PhilReedData** [comment]
Thanks, I certainly will try that locally. Which remote call should I use now? To a particular tag/release of ETT?

**Comment by bedroesb** [comment]
@PhilReedData `remote_theme: PhilReedData/elixir-toolkit-theme@page-logos-3.2.0`

**Comment by bedroesb** [comment]
I don't think you have pulled the latest version of your branch? can you check?

**Comment by bedroesb** [comment]
@phil, can you point me to a place/branch where you try out the FAIRDOM Seek website with this version of the theme? The second screenshot show the logo to be be squeezed for example. and I think I want to play a little bit more with the spacings.

**Comment by PhilReedData** [comment]
Sure, it is here: https://github.com/FAIRdom/fairdom.github.io/tree/page-logos

**Comment by bedroesb** [comment]
I think most of the weird thing are gone now:

image

image

**Comment by bedroesb** [comment]
It's still giving me trouble with the TOC, Maybe we should make use of the TOC and put it above? 

image

**Comment by PhilReedData** [comment]
I deleted the local 'section-navigation-tiles.html' file, I don't know why we had that. Your code appears to be working now. 
image
image

That is a good point about the TOC, I didn't think of that. Yes, putting it within the column of the TOC at the top sounds wise, the same (max) width. Is that a conditional statement? to include the logo where it is, unless there is a TOC in which case put it there.

**Comment by bedroesb** [comment]
@PhilReedData 
image

**Comment by bedroesb** [comment]
This looks a lot better to me!

**Comment by PhilReedData** [comment]
Agreed!

**Comment by bedroesb** [comment]
@PhilReedData just tried in on you FAIRDOM brannch. It works well, but I suggest to enable everywhere the toc. (so deleting toc:false). This will help with svg's not having a width or height. (or otherwhise add them manually). I can not find a solution that works for all image dimensions.

**Comment by bedroesb** [comment]
If you give green light on this one I will merge!

**Comment by bedroesb** [comment]
@PhilReedData take my words back! I just made it working in every scenario (I think) 
If you could double check that would be great!

**Comment by PhilReedData** [comment]
Sure, I'm testing now, taking out the toc: false statements...

**Comment by bedroesb** [comment]
But I think the TOC is a nice adition anyway ... but that's personal

**Comment by PhilReedData** [comment]
For some reason, the HITS project page wouldn't show its logo until I added a few subheadings (h2) into the page. The others are working fine, showing the image regardless of toc true/false.

image
^ when there is no h2 content in the page

image
^ when there is no h2 content in the page and toc: false

image
^ when I add at least one h2 line

image
^ when I add at least one h2 line and toc: false

Is there a bug?

**Comment by PhilReedData** [comment]
The FAIRDOM Communities page, it has some h2 headings, and toc: false, and it adds a blank right column anyway that was not there before. 
image
I am adding a TOC there now anyway, but it looks like an unintended side effect of this work.

**Comment by PhilReedData** [comment]
That has worked, thanks! 
image

**Comment by bedroesb** [comment]
Good catch btw. That was a bug. I think I am only now happy with all user scenarios. Sorry for all the changes! My conditional was not behaving as expected...

**Comment by PhilReedData** [comment]
No worries, it is good to catch these things now. 
One more possible bug, when I mouse over the section title, I have a CSS animation like with the RO-Crate site. It reflows the text which briefly runs onto another line, then back again. I think this has happened since adding the page image to the tile. 
ETTanimation
I have only seen this with one of our tiles, it happens to be the right length of text to be borderline whether a new line is required or not. Do you have any thoughts on this?

**Comment by PhilReedData** [comment]
Similar with one other tile, but it doesn't resize.
 ETTanimation2

**Comment by bedroesb** [comment]
@PhilReedData THis is unrelated to the changes here, but is related to the hover effect put in place. If the description is is causing an edge case where it is longer that the width it has + a small change in width available, the text wrapping will get triggered. This might not have been the case in the past, since there was more width available. But I can give you an example where this is already the case: https://www.infectious-diseases-toolkit.org/showcase/ first tile. 

You will have to play around with the hover effect you've set in your css.

**Comment by bedroesb** [comment]
I think put a slight delay on the shrink of the width compared to the growth on the right side, could fix this.

**Comment by PhilReedData** [comment]
Ah I see, thanks anyway. I had a look but I'm already using the same code as your example. It is a rare problem, only happens at specific widths, and if you say it's not been introduced by the page image work then I'll leave it alone for now.

What comes next? Is this work ready to go in the next ETT release, and should I wait for that before merging into the production FAIRDOM website?

**Comment by bedroesb** [comment]
I could still Iron out some behaviours while testing it on other instances

**Comment by bedroesb** [comment]
@PhilReedData I think we are kind of in a good state? I tried in in the ELIXIR toolkit theme, the FAIRDOM website (with and without toc), RDMkit and Infectious diseases toolkit. Tried out multiple breaking points. If you could maybe check out on Safari.

**Review by bedroesb — APPROVED** [review]

**Comment by bedroesb** [comment]
@PhilReedData once I have released a new version, you can use that one in your FAIRDOM instance!

**Comment by PhilReedData** [comment]
Here are my Safari tests with FAIRDOM:
image
image
image
image

image
^ FAIRDOMHub page is not showing the image in Safari, but is in Chrome. 
image
More precisely, the image flashes up for less than a second at load.

When I take out toc: false, the image disappears on both.
image
image

If I add a (temporary) h2, the image reappears on Chrome only.
image
image

This problem does not happen on the SEEK page, which is otherwise the same (toc: false). 
Perhaps the [choice of image](https://fair-dom.org/images/fairdom_in_use/fairdomhub-logo.svg) on the FAIRDOMHub page is a factor.

**Comment by PhilReedData** [comment]
Good news, restarting my local server has fixed the problem serving the FAIRDOMHub logo, strangely.
image
I've noticed that there is more white space before the footer now. 
image
Testing the middle breakpoint.

**Comment by bedroesb** [comment]
@PhilReedData I think this will be a caching thing, since I had to update some javascript and that does not get a unique identifier. Let me improve that!

**Comment by bedroesb** [comment]
Normally this should not happen anymore

**Review by bedroesb — APPROVED** [review]

**Pull request merged**
