### PR TITLE
Better alignment of footer elements in mobile mode

### LINKED ISSUE #266: Footer links and logos get out of line on tablet-sized screens
While checking on different display resolutions, I did notice that the other footer links and logos get out of line on tablet-sized screens:

screenshot showing dimensions of iPad Air in portrait mode, with footer links and logos misaligned

_Originally posted by @elichad in https://github.com/ELIXIR-Belgium/elixir-toolkit-theme/issues/260#issuecomment-2248501483_

### PR DESCRIPTION
**Pull request by bedroesb**
This will close #266 

Before:

image

After:

image

### CODE REVIEW

**Comment by bedroesb** [comment]
This was originally noticed by you @elichad, what do you think?

**Comment by elichad** [comment]
Definitely an improvement, though still looks a bit disjointed to me since the text and logos are all mixed up. Maybe logos in one column and text in the other, if that's possible? Or text above and logos below.

**Comment by bedroesb** [comment]
Sadly that would cause a complete reshuffle of the content, which I would like to prevent, to not confuse people, if they resize their window. Because these footers are completely customization, they can come in many shapes / combinations.

**Comment by bedroesb** [comment]
Since this is the best I can get it for now, without making to many assumptions, I will merge this PR. If you have new ideas, please don't hesitate to open an issue about it!

**Pull request merged**
