### PR TITLE
Include collections (site.documents) in search

### LINKED ISSUE #265: Search feature does not include pages from collections
For an example in deployment, see https://github.com/ResearchObject/ro-crate/issues/336. Our specification pages are in a Jekyll collection within our [repo](https://github.com/ResearchObject/ro-crate/tree/main/docs) (i.e. not under `pages/` but under `_specification`), and they don't show up in search results because of this.

I've had a poke around the search code and I think the problem is here:
https://github.com/ELIXIR-Belgium/elixir-toolkit-theme/blob/main/assets/js/search-data.json#L8

Namely that `site.html_pages` doesn't appear to include pages from collections.

## Possible solution

I found that I could add one extra line to include the missing pages into the search (without duplicating the other pages) - [site.documents](https://jekyllrb.com/docs/variables/#site-variables) provides "A list of all the documents in every collection."
```
...
{%- assign pages_array = "" | split: "" -%}
{%- assign pages_array = pages_array | push: site.html_pages -%}
{%- assign pages_array = pages_array | push: site.documents -%} # this is added
{%- for pages in pages_array -%}
...
```

This will work for our site but I'm not sure if it will work for every site that uses the theme. @bedroesb could you let me know if this is something that you can incorporate in the base theme? If you know of an alternative solution I welcome that too.

### PR DESCRIPTION
**Pull request by elichad**
fixes #265

### CODE REVIEW

**Review by bedroesb — APPROVED** [review]
Works for me

**Comment by elichad** [comment]
Thanks @bedroesb ! When will the next ETT version containing this fix be released?

**Comment by bedroesb** [comment]
@elichad a new release has been made: https://github.com/ELIXIR-Belgium/elixir-toolkit-theme/releases 

Thank you for your contributions!

**Comment by bedroesb** [comment]
@elichad I had to create a patch release because of an unforeseen scenario with the tools table. Sorry for this inconvenience. 3.1.1 should not have the problem of showing the Tools and resources heading when not needed.

**Pull request merged**
