### PR TITLE
Improved contributors tiles and carousel fix

### LINKED ISSUE #307: Hanging </div> visible when no contributors found on Editorial Board page
I noticed a small bug when listing all contributors with "editor" role on Editorial Board page - when the list is empty then perhaps there should not be an empty carousel but a note saying something like "No contributors found". This has nothing to do with filtering contributors by the role btw. - it's just where I noticed the bug.

There is a hanging closing </div> tag which is mistake somewhere in https://github.com/ELIXIR-Belgium/elixir-toolkit-theme/blob/main/_includes/contributor-carousel-selection.html (but I could not figure out which one it is - my suspicion is on the line 47: https://github.com/ELIXIR-Belgium/elixir-toolkit-theme/blob/main/_includes/contributor-carousel-selection.html#L47 but it is not as simple as that). 

This hanging </div> tag is only visible on the page when the contributors list is empty - but it is always there just browsers are good at ignoring it.

See the screenshot with issue:

image

The hanging </div> tag present even when the contributors list is not empty.

image

### PR DESCRIPTION
**Pull request by bedroesb**
- Some code refactoring
- The filtering based on role was not working well, this should be fixed now
- Also handling of no contributors are improved. 

This will close #307

### CODE REVIEW

**Comment by bedroesb** [comment]
@anenadic Hope this fixes your bug!

**Comment by bedroesb** [comment]
I will wait for the new release until this one is approved and merged, this is an obvious bug!

**Comment by bedroesb** [comment]
@anenadic I just realize that I merged the PR to prepare for a new release to soon, and now the new version is in the README. If ok for you would like to merge this one, and create a new release today.

**Comment by anenadic** [comment]
All good here - thank you.

**Pull request merged**
