### PR TITLE
Add dedicated field for ELIXIR node

### PR DESCRIPTION
**Pull request by unode**
Include a dedicated field to specify the ELIXIR node affiliation.

This is being proposed as a follow up of https://github.com/elixir-europe-training/ELIXIR-Training-SPLASH/pull/132 where node affiliation was being specified with an arbitrary (and inconsistent) style across different contribution sections.

### CODE REVIEW

**Comment by bedroesb** [comment]
@unode Thanks a lot for your contribution! I was wondering making the node look visually different than the Affiliation instead of adding a break line would be nice? In its current shape the card gets higher by default when a node is added. Second though: is for non ELIXIR people clear what the word "node" means? The theme is also used in for example Australian BioComons

**Comment by unode** [comment]
I initially named the field `elixirnode` but seemed unnecessarily verbose. Do you think it would be clearer? Perhaps with an underscore: `elixir_node`?

As for style, I played around with the badges like currently used for author/editor role but I didn't really find a visual that I liked. Ended up going with the simplest option that could be further modified if necessary. Do any visuals come to mind straight away?

I also played with the idea of having a built-in link to the node or a flag but not all nodes are countries (e.g. Hub and EMBL-EBI). Also went back and forth between full node name and short code. The last seems to be most frequently used and some nodes (e.g. UK) don't use a long version at all.

**Comment by bedroesb** [comment]
I have been looking at this from a distance and I have to admit that I am not sure whether this is an improvement. As seen in https://rdmkit.elixir-europe.org/contributors it would really make almost all rows taller. Not putting a new line does not add much besides consistency IMO. Could the consistent use of delimiters not be enforced by the editors of a repo? This way it is more versatile because many of theme have besides a department and elixir node, also  a university/institute affiliation and they all better get delimited consistently anyway.

**Comment by unode** [comment]
The problem is not the consistent use of a delimiter but that using it (more than using it inconsistently) causes [some issues](https://elixir-europe-training.github.io/ELIXIR-Training-SPLASH/contributors) - See for instance Renato Alves that shows up multiple times.

Looking for ways to make progress here, if the issue is simply one of style, can we explore other visuals that allow displaying the information without the concern that the rows become taller?

**Comment by bedroesb** [comment]
The problem you describe is not related to the affiliation? This person just described himself 2 times with different names. It is not only a style thing, but more that the problems are caused by not having a "style guide" that is enforced onto the repo. The fact that  Renato Alves put his node in his name should never have been merged in the first place. That is just wrong ....

**Comment by bedroesb** [comment]
the fact that Renato Alves did not use the affiliation in the first place, means that having an elixir_node attribute would not solve this particular problem. Sorry I just try to understand the reasoning here :)

**Comment by bedroesb** [comment]
I see now the problem. The `name` attribute is wrongly used as a way to also add the affiliation. This is not allowed and described in the CONTRIBUTORS file:

```yml
# reference maintainers/contributors by their name used in contributors metadata section on the pages.
# Extra metadata that is possible to add:
# Full Name:
#    git: github id
#    email: email adress
#    orcid: ocrid id
#    role: the role of the contributor
#    affiliation: affiliation
#    image_url: absolute path to image (default image from github)

```

And make sure you always use the same name in the metadata of the page (the list of contributors) and in the CONTRIBUTORS file. This explains the doubles. https://elixir-belgium.github.io/elixir-toolkit-theme/page_mechanics#possible-metadata-attributes-of-a-page also describes:

`contributors:` List here all the contributors that helped in establishing the page. This will be the full name of the person. Make sure that the person name that is listed can be found in the CONTRIBUTORS.yaml file in the _data directory if you want to link the github id and other contact information.

**Comment by bedroesb** [comment]
Thanks a lot for your extensive insight. I do have some remarks:

1. This is the whole purpose of this theme, community driven contributions to one website. The theme is very actively used in even bigger communities than Splash, but off course with an editorial board in place doing polishing of every pull request, to prevent the exact problem.

This is also related to the other points you mention. I do not believe that without a style guide that is enforced by editors, the problem will be solved. People can still have affiliations in any form or shape, since it is free text. for example `INSTRUCT-ERIC / National Center for Biotechnology (CNB-CSIC)` 

5. I would not make use of the newline for reasons I described before. And the problem with another separator is that it will look the best when it is the same style as the other separators used in the affiliation, coming back at my first point. 

Let me have a look in a way of adding the node in a less space taking way. But this does not take my opinion away that the biggest problem is the lack of decision in the community how the contributors should describe their affiliation and enforcing it, hence the creation of this issue ;)

**Comment by unode** [comment]
Thanks Bert, I'll keep an eye on this PR/issue and modify the upstream PR once there's a final decision and implementation here.

Let me know as well what you think about the idea to fail to build if fields (or other content) are not used in the intended way.

**Comment by unode** [comment]
Thanks Bert, yes feel free to close

**Pull request closed without merging**
